utils::globalVariables(c(".I",
                         ".",
                         ":=",
                         "row_id",
                         "text",
                         "lang",
                         "lang_prob",
                         "lang_guess",
                         "text_clean",
                         "text_orig",
                         "..cols_exist",
                         "error",
                         "lang_target",
                         "tl_datetime",
                         "tl_model",
                         "translation",
                         "return_string"
                         )
)
